import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { getCodexCapabilities } from "./codex/capabilities.js";

const defaultVaultPath = "/Users/nichikatanaka/Documents/Obsidian Vault";
const defaultStartHereSubdir = "00_Start Here";
const defaultResumeContractPath = join(process.cwd(), "data", "resume-contract.json");
const resumeRule =
  "Before asking the user to restate context, read resume-contract.json, Project Handoff Index, Resume Current Work, and each project STATE/artifacts locator. Treat generated handoff notes as locators, not completion proof. Natural resume questions for any project or workflow, such as 'AutomationOSは何をやっていた?', '<project>は何をやっていた?', 'あと何をやる?', 'どこまで進んだ?', 'PCが落ちたので続きから', or '前回の続き', must trigger this read-first path automatically, even when the user does not explicitly mention Obsidian, STATE.md, or artifacts.";
const naturalResumeTriggerNote =
  "Use this for any project whenever the user asks what was being done, what remains, where to resume, or after a crash/new session. First read the locators, then fresh-read the project-owned STATE.md, automation.toml, Skill/docs, queues/readbacks, and latest artifacts before answering.";
const artifactScanMaxDepth = 3;
const artifactScanMaxFiles = 200;
const artifactScanMaxEntries = 1000;

export type ResumeContractLocator = {
  label: string;
  path: string;
  kind: string;
  exists: boolean;
  note: string;
};

export type ResumeContractProject = {
  name: string;
  cwd: string;
  authorityFiles: ResumeContractLocator[];
  latestArtifact: ResumeContractLocator | null;
  memoryHints: ResumeContractLocator[];
  locators: ResumeContractLocator[];
};

export type ResumeContract = {
  readFirst: ResumeContractLocator[];
  projects: ResumeContractProject[];
  authorityFiles: ResumeContractLocator[];
  latestArtifact: ResumeContractLocator | null;
  memoryHints: ResumeContractLocator[];
  resumeRule: string;
  generatedAt: string;
};

export type ResumeContractOptions = {
  vaultPath?: string;
  startHereSubdir?: string;
  contractPath?: string;
  codexMemoryFile?: string;
  generatedAt?: string;
};

type FileScanBudget = {
  files: string[];
  entriesVisited: number;
  maxDepth: number;
  maxFiles: number;
  maxEntries: number;
};

export function resolveResumeContractPath(input?: string): string {
  return resolve(input ?? process.env.AUTOMATION_OS_RESUME_CONTRACT_PATH ?? defaultResumeContractPath);
}

export function buildResumeContract(options: ResumeContractOptions = {}): ResumeContract {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const vaultPath = resolve(options.vaultPath ?? process.env.AUTOMATION_OS_OBSIDIAN_VAULT ?? defaultVaultPath);
  const startHereDir = join(vaultPath, options.startHereSubdir ?? defaultStartHereSubdir);
  const contractPath = resolveResumeContractPath(options.contractPath);
  const projectHandoffIndex = join(startHereDir, "Project Handoff Index.md");
  const resumeCurrentWork = join(startHereDir, "Resume Current Work.md");
  const projectMemoryMap = join(startHereDir, "Project Memory Map.md");
  const resumeContractNote = join(startHereDir, "Resume Contract.md");
  const userAgentsFile = join(homedir(), "AGENTS.md");
  const codexAgentsFile = join(homedir(), ".codex", "AGENTS.md");
  const globalAuthorityFiles = [
    locator("User AGENTS", userAgentsFile, "authority-file", "User-level Codex instructions. Read before asking the user to restate context."),
    locator("Codex AGENTS", codexAgentsFile, "authority-file", "Codex user-level instructions and resume guardrails.")
  ];
  const memoryFile = resolve(options.codexMemoryFile ?? process.env.AUTOMATION_OS_CODEX_MEMORY_FILE ?? join(homedir(), ".codex", "memories", "MEMORY.md"));
  const memoryHints = readMemoryHints(memoryFile);
  const projectRoots = collectProjectRoots({ projectHandoffIndex, memoryHints });
  const projects = projectRoots.map((cwd) => buildProjectContract(cwd, { projectHandoffIndex, resumeCurrentWork, projectMemoryMap, memoryHints }));
  const authorityFiles = uniqueLocators([...globalAuthorityFiles, ...projects.flatMap((project) => project.authorityFiles)]);
  const latestArtifact = selectLatestLocator(projects.map((project) => project.latestArtifact).filter((locator): locator is ResumeContractLocator => Boolean(locator)));

  return {
    readFirst: [
      locator("Resume contract JSON", contractPath, "resume-contract-json", "Machine-readable handoff contract generated by Automation OS."),
      locator("User AGENTS", userAgentsFile, "authority-file", "User-level Codex instructions. Read before asking the user to restate context."),
      locator("Codex AGENTS", codexAgentsFile, "authority-file", "Codex user-level instructions and resume guardrails."),
      locator("Project Handoff Index", projectHandoffIndex, "obsidian-handoff-index", "Existing stop-hook locator. Read only; Automation OS export does not overwrite it."),
      locator("Resume Current Work", resumeCurrentWork, "obsidian-resume-brief", "Generated short resume brief for the latest Automation OS context."),
      locator("Project Memory Map", projectMemoryMap, "obsidian-project-memory-map", "Generated project/session locator map."),
      locator("Resume Contract note", resumeContractNote, "obsidian-resume-contract", "Human-readable view of this contract.")
    ],
    projects,
    authorityFiles,
    latestArtifact,
    memoryHints: memoryHints.slice(0, 12),
    resumeRule,
    generatedAt
  };
}

export function writeResumeContract(contract: ResumeContract, contractPath = resolveResumeContractPath()): string {
  const path = resolveResumeContractPath(contractPath);
  mkdirSync(dirname(path), { recursive: true });
  const tmpPath = `${path}.${process.pid}.${Date.now()}.tmp`;
  writeFileSync(tmpPath, `${JSON.stringify(contract, null, 2)}\n`);
  renameSync(tmpPath, path);
  return path;
}

export function readResumeContractFile(contractPath = resolveResumeContractPath()): ResumeContract | null {
  const path = resolveResumeContractPath(contractPath);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as ResumeContract;
  } catch {
    return null;
  }
}

export function getResumeContract(options: ResumeContractOptions = {}): ResumeContract {
  return buildResumeContract(options);
}

export function renderResumeContractMarkdown(contract: ResumeContract): string {
  return [
    "---",
    "system: automation-os",
    "generated_by: automation-os",
    "kind: resume-contract",
    "status: active",
    "priority: high",
    `generated_at: ${contract.generatedAt}`,
    "---",
    "",
    "# Resume Contract",
    "",
    "Codex が再開時に最初に読む契約です。ここは locator であり、完了証跡そのものではありません。",
    "",
    "## Read First",
    "",
    ...contract.readFirst.map((entry) => `- ${entry.label}: \`${entry.path}\` (${entry.exists ? "exists" : "missing"})`),
    "",
    "## Resume Rule",
    "",
    contract.resumeRule,
    "",
    "## Natural Resume Triggers",
    "",
    "- AutomationOSは何をやっていた?",
    "- <project>は何をやっていた?",
    "- あと何をやる?",
    "- どこまで進んだ?",
    "- PCが落ちた / セッションが変わった / 前回の続き",
    "",
    naturalResumeTriggerNote,
    "",
    "## Projects",
    "",
    ...(contract.projects.length ? contract.projects.flatMap(renderProjectMarkdown) : ["No project locators found."]),
    "",
    "## Latest Artifact",
    "",
    contract.latestArtifact ? `- ${contract.latestArtifact.path}` : "- none",
    "",
    "## JSON",
    "",
    `- Source: \`${contract.readFirst[0]?.path ?? "data/resume-contract.json"}\``
  ].join("\n");
}

function renderProjectMarkdown(project: ResumeContractProject): string[] {
  return [
    `### ${project.name}`,
    "",
    `- CWD: \`${project.cwd}\``,
    `- Latest artifact: ${project.latestArtifact ? `\`${project.latestArtifact.path}\`` : "none"}`,
    `- Authority files: ${project.authorityFiles.length ? project.authorityFiles.map((file) => `\`${file.path}\``).join(", ") : "none found"}`,
    `- Memory hints: ${project.memoryHints.length ? project.memoryHints.map((hint) => hint.note).join("; ") : "none"}`,
    ""
  ];
}

function collectProjectRoots(input: { projectHandoffIndex: string; memoryHints: ResumeContractLocator[] }): string[] {
  const roots = new Set<string>();
  addProjectRoot(roots, homedir());
  addProjectRoot(roots, join(homedir(), ".codex"));
  addProjectRoot(roots, process.cwd());
  addProjectRoot(roots, "/Users/nichikatanaka/Documents/Codex/automation-os");
  for (const automation of getCodexCapabilities().capabilities.automations) {
    addProjectRoot(roots, automation.path.endsWith("automation.toml") ? dirname(expandHome(automation.path)) : expandHome(automation.path));
  }
  for (const hint of input.memoryHints) addProjectRoot(roots, hint.path);
  if (existsSync(input.projectHandoffIndex)) {
    for (const path of extractAbsolutePaths(safeReadText(input.projectHandoffIndex))) addProjectRoot(roots, path);
  }
  return Array.from(roots).slice(0, 24);
}

function buildProjectContract(
  cwd: string,
  input: {
    projectHandoffIndex: string;
    resumeCurrentWork: string;
    projectMemoryMap: string;
    memoryHints: ResumeContractLocator[];
  }
): ResumeContractProject {
  const authorityFiles = [
    "STATE.md",
    "AGENTS.md",
    "automation.toml",
    "SKILL.md",
    join("docs", "current-run-contract.md"),
    join("docs", "CURRENT.md")
  ].map((entry) => locator(entry, join(cwd, entry), "authority-file", "Project-owned source of truth or resume boundary."))
    .filter((entry) => entry.exists);
  const latestArtifact = findLatestArtifact(cwd);
  const projectHints = input.memoryHints.filter((hint) => pathsMayReferToSameProject(cwd, hint.path)).slice(0, 4);
  return {
    name: basename(cwd) || cwd,
    cwd,
    authorityFiles,
    latestArtifact,
    memoryHints: projectHints,
    locators: [
      locator("Project Handoff Index", input.projectHandoffIndex, "obsidian-handoff-index", "Existing generated stop-hook locator."),
      locator("Resume Current Work", input.resumeCurrentWork, "obsidian-resume-brief", "Generated Automation OS resume brief."),
      locator("Project Memory Map", input.projectMemoryMap, "obsidian-project-memory-map", "Generated project/session locator map.")
    ].filter((entry) => entry.exists)
  };
}

function findLatestArtifact(cwd: string): ResumeContractLocator | null {
  const candidates = [join(cwd, "artifacts"), join(cwd, "data", "artifacts")].filter((path) => existsSync(path));
  const budget = createFileScanBudget();
  for (const path of candidates) {
    listFilesBounded(path, 0, budget);
    if (isFileScanBudgetExhausted(budget)) break;
  }
  const files = budget.files;
  if (!files.length) return null;
  const latest = files
    .map((path) => ({ path, mtime: safeMtime(path) }))
    .sort((a, b) => b.mtime - a.mtime)[0];
  return locator("Latest artifact", latest.path, "artifact", "Most recently modified local artifact under the project.");
}

function createFileScanBudget(): FileScanBudget {
  return {
    files: [],
    entriesVisited: 0,
    maxDepth: artifactScanMaxDepth,
    maxFiles: artifactScanMaxFiles,
    maxEntries: artifactScanMaxEntries
  };
}

function isFileScanBudgetExhausted(budget: FileScanBudget): boolean {
  return budget.files.length >= budget.maxFiles || budget.entriesVisited >= budget.maxEntries;
}

function listFilesBounded(dir: string, depth: number, budget = createFileScanBudget()): string[] {
  if (depth > budget.maxDepth || isFileScanBudgetExhausted(budget)) return budget.files;
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return budget.files;
  }
  for (const entry of entries) {
    if (entry.startsWith(".")) continue;
    if (isFileScanBudgetExhausted(budget)) break;
    budget.entriesVisited += 1;
    const path = join(dir, entry);
    try {
      const stat = lstatSync(path);
      if (stat.isDirectory()) {
        listFilesBounded(path, depth + 1, budget);
      } else if (stat.isFile()) {
        budget.files.push(path);
      }
    } catch {
      continue;
    }
  }
  return budget.files;
}

function readMemoryHints(memoryFile: string): ResumeContractLocator[] {
  if (!existsSync(memoryFile)) return [];
  const hints: ResumeContractLocator[] = [];
  for (const line of safeReadText(memoryFile).split("\n").slice(0, 2500)) {
    for (const path of extractMemoryPaths(line)) {
      hints.push(locator("Codex memory hint", path, "memory-hint", shortSnippet(line.replace(/^\s*[-#]+\s*/, ""), 180)));
    }
  }
  return uniqueLocators(hints).slice(0, 80);
}

function extractMemoryPaths(line: string): string[] {
  const paths: string[] = [];
  for (const match of line.matchAll(/scope:\s*`([^`]+)`/g)) paths.push(match[1].trim());
  for (const match of line.matchAll(/\bcwd(?:_family)?=([^;\),\n]+)/g)) {
    const raw = match[1].trim().replace(/^`|`$/g, "");
    paths.push(...raw.split(/\s+and\s+|,\s*/).map((entry) => entry.trim()));
  }
  return paths.map((path) => path.replace(/^`|`$/g, "")).filter((path) => path.startsWith("/") || path.startsWith("~/"));
}

function extractAbsolutePaths(markdown: string): string[] {
  const paths = new Set<string>();
  for (const match of markdown.matchAll(/(?:`|^|\s)(\/Users\/nichikatanaka\/[^\s`),;]+)/g)) {
    paths.add(match[1].replace(/[.:]+$/, ""));
  }
  return Array.from(paths);
}

function addProjectRoot(roots: Set<string>, inputPath: string): void {
  const normalized = normalizePath(inputPath);
  if (!normalized) return;
  const projectRoot = trimToProjectRoot(normalized);
  roots.add(projectRoot);
}

function trimToProjectRoot(path: string): string {
  const artifactIndex = path.split("/").findIndex((part) => part === "artifacts");
  if (artifactIndex > 0) return path.split("/").slice(0, artifactIndex).join("/");
  for (const marker of ["STATE.md", "AGENTS.md", "automation.toml", "SKILL.md"]) {
    if (path.endsWith(`/${marker}`)) return dirname(path);
  }
  return path;
}

function locator(label: string, path: string, kind: string, note: string): ResumeContractLocator {
  const resolved = normalizePath(path) ?? path;
  return {
    label,
    path: resolved,
    kind,
    exists: existsSync(resolved),
    note
  };
}

function uniqueLocators(locators: ResumeContractLocator[]): ResumeContractLocator[] {
  const seen = new Set<string>();
  return locators.filter((locator) => {
    const key = `${locator.kind}\n${locator.path}\n${locator.note}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function selectLatestLocator(locators: ResumeContractLocator[]): ResumeContractLocator | null {
  if (!locators.length) return null;
  return locators.sort((a, b) => safeMtime(b.path) - safeMtime(a.path))[0];
}

function pathsMayReferToSameProject(left: string, right: string): boolean {
  const normalizedLeft = normalizePath(left);
  const normalizedRight = normalizePath(right);
  if (!normalizedLeft || !normalizedRight) return left === right;
  return isSameOrInside(normalizedLeft, normalizedRight) || isSameOrInside(normalizedRight, normalizedLeft);
}

function isSameOrInside(path: string, root: string): boolean {
  const rel = relative(root, path);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function normalizePath(path: string): string | undefined {
  const trimmed = path.trim().replace(/^`|`$/g, "");
  if (!trimmed) return undefined;
  return resolve(isAbsolute(expandHome(trimmed)) ? expandHome(trimmed) : join(process.cwd(), expandHome(trimmed)));
}

function expandHome(path: string): string {
  if (!path.startsWith("~/")) return path;
  return join(process.env.AUTOMATION_OS_CAPABILITIES_HOME ?? homedir(), path.slice(2));
}

function safeMtime(path: string): number {
  try {
    return statSync(path).mtimeMs;
  } catch {
    return 0;
  }
}

function safeReadText(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}

function shortSnippet(value: string, max: number): string {
  const compact = value.replace(/\s+/g, " ").trim();
  return compact.length > max ? `${compact.slice(0, max - 3)}...` : compact;
}
